FROM python:3.10-slim

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    procps \
    gzip \
    build-essential \
    python3-dev \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    && rm -rf /var/lib/apt/lists/*

# Install PAnno
RUN pip install --no-cache-dir panno==0.3.1

# Clean up
RUN apt-get clean
# ENTRYPOINT ["/bin/bash"]
